### ISSUE TITLE
3.1 redmine, starts in an a failed state when installing this plugin

### ISSUE THREAD

**Issue by web-engineer** [alexandermeindl/redmine_tweaks#20]
Installed by cd'ing to my redmine directory and running -
```
git clone https://github.com/alexandermeindl/redmine_tweaks.git plugins/redmine_tweaks
```
The git:// url as in your install instructions wouldn't work.

Error was -
```
"We're sorry, but something went wrong."
```
I think this is the error from the logs -
```
[ 2015-09-04 09:58:04.5659 50899/7f4bf1d84700 App/Implementation.cpp:303 ]: Could not spawn process for application /var/www/html/redmine/: An error occured while starting up the preloader.
  Error ID: ba346869
  Error details saved to: /tmp/passenger-error-rcaDfj.html
  Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>

  <pre class="commands">bundle install</pre>

<p>If that didn't work, then maybe the problem is that your gems are installed to <code>/var/www/.rvm/gems</code>, while at the same time you set <code>PassengerRuby</code> (Apache) or <code>passenger_ruby</code> (Nginx$

<p>To make RVM load gems from the home directory, you need to set <code>PassengerRuby</code>/<code>passenger_ruby</code> to an RVM wrapper script inside the home directory:</p>

<ol>
  <li>Login as apache.</li>
  <li>Enable RVM mixed mode by running:
      <pre class="commands">rvm user gemsets</pre></li>
  <li>Run this to find out what to set <code>PassengerRuby</code>/<code>passenger_ruby</code> to:
      <pre class="commands">/usr/local/rvm/gems/ruby-2.2.3/wrappers/ruby \
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.16/bin/passenger-config --detect-ruby</pre></li>
</ol>

<p>If that didn't help either, then maybe your application is being run under a different environment than it's supposed to. Please check the following:</p>

<ol>
  <li>Is this app supposed to be run as the <code>apache</code> user?</li>
  <li>Is this app being run on the correct Ruby interpreter? Below you will
      see which Ruby interpreter Phusion Passenger attempted to use.</li>
  <li>Please check whether the correct RVM gemset is being used.</li>
  <li>Sometimes, RVM gemsets may be broken.
      <a href="https://github.com/phusion/passenger/wiki/Resetting-RVM-gemsets">Try resetting them.</a></li>
</ol>

<p>-------- The exception is as follows: -------</p>
Could not find gem &#39;brakeman (&gt;= 0) ruby&#39; in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
<pre>  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/resolver.rb:347:in `block in verify_gemfile_dependencies_are_found!&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/resolver.rb:325:in `each&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/resolver.rb:325:in `verify_gemfile_dependencies_are_found!&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/resolver.rb:198:in `start&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/resolver.rb:182:in `resolve&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/definition.rb:200:in `resolve&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `&lt;top (required)&gt;&#39;
  /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require&#39;
  /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.16/lib/phusion_passenger/loader_shared_helpers.rb:406:in `activate_gem&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.16/lib/phusion_passenger/loader_shared_helpers.rb:288:in `block in run_load_path_setup_code&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.16/lib/phusion_passenger/loader_shared_helpers.rb:411:in `running_bundler&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.16/lib/phusion_passenger/loader_shared_helpers.rb:287:in `run_load_path_setup_code&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.16/helper-scripts/rack-preloader.rb:99:in `preload_app&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.16/helper-scripts/rack-preloader.rb:153:in `&lt;module:App&gt;&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.16/helper-scripts/rack-preloader.rb:29:in `&lt;module:PhusionPassenger&gt;&#39;
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.16/helper-scripts/rack-preloader.rb:28:in `&lt;main&gt;&#39;</pre>
```

**Comment by web-engineer** [comment]
Worked this out...

Answer was in the log above - after cloneing (using the https address for me worked) I needed to run -

```
bundle install
```

looks like this plugin uses gem's that the core product didn't come pre-installed with - perhaps the docs need updating to ensure a smooth install for simpletons like me...
